name: Lint
on: workflow_call
jobs:
  lint_project:
    name: 'Lint project'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run lint
